// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRegion = "sys_region"

// SysRegion mapped from table <sys_region>
type SysRegion struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:地区主键编号" json:"id"` // 地区主键编号
	Name       string `gorm:"column:name;comment:地区名称" json:"name"`                             // 地区名称
	ShortName  string `gorm:"column:short_name;comment:简称" json:"short_name"`                   // 简称
	Code       string `gorm:"column:code;comment:行政地区编号" json:"code"`                           // 行政地区编号
	ParentCode string `gorm:"column:parent_code;comment:父id" json:"parent_code"`                // 父id
	/*
		1级：省、直辖市、自治区
		2级：地级市
		3级：市辖区、县（旗）、县级市、自治县（自治旗）、特区、林区
		4级：镇、乡、民族乡、县辖区、街道
		5级：村、居委会
	*/
	Level int32 `gorm:"column:level;comment:1级：省、直辖市、自治区\n2级：地级市\n3级：市辖区、县（旗）、县级市、自治县（自治旗）、特区、林区\n4级：镇、乡、民族乡、县辖区、街道\n5级：村、居委会" json:"level"`
	Flag  int32 `gorm:"column:flag;comment:0:正常 1废弃" json:"flag"` // 0:正常 1废弃
}

// TableName SysRegion's table name
func (*SysRegion) TableName() string {
	return TableNameSysRegion
}
