server:
  port: 7001
#mybatis:
#  type-handlers-package: com.my.model.enums.crowdfunding


spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  task:
    execution:
      pool:
        max-threads: 100
app:
  id: my-test

